// DKMP Tür Eylem Planları sayfasından alınan liste (91 tür).
// https://www.tarimorman.gov.tr/DKMP/Menu/49/Tur-Eylem-Planlari
export const BASE_PDF = 'https://www.tarimorman.gov.tr/DKMP/Belgeler/TÜR%20EYLEM%20PLANI/';

// [ad, bilimsel ad, pdf]
export const fauna = [
  ['Ağrı Kertenkelesi', 'Darevskia unisexualis', 'AgrKrtenk.pdf'],
  ['Akbez Geyik Böceği', 'Lucanus cervus', 'Akbz_geykbcg.pdf'],
  ['Alageyik', 'Dama dama', 'Alageyik.pdf'],
  ['Anadolu Engereği', 'Vipera anatolica', 'AndlEngrek.pdf'],
  ['Avrupa Kırmızı Orman Karıncası', 'Formica pratensis', 'Avrormankar.pdf'],
  ['Iğdır Çöl Faresi', 'Meriones dahli', 'Colfaresi.pdf'],
  ['Çizgili Sırtlan', 'Hyaena hyaena', 'CzgSirtlan.pdf'],
  ['Hatay Dağ Ceylanı', 'Gazella gazella', 'Dagceylan.pdf'],
  ['Dağ Horozu', 'Lyrurus mlokosiewiczi', 'Daghorozu.pdf'],
  ['Beyazbantlı Dağ Engereği', 'Montivipera albizona', 'DgEngrek.pdf'],
  ['Fırat Kaplumbağası', 'Rafetus euphraticus', 'Firat_kap.pdf'],
  ['Hopa Engereği', 'Vipera darevskii', 'HopaEngrk.pdf'],
  ['İskenderun Kertenkelesi', 'Acanthodactylus schreiberi', 'İskenKert.pdf'],
  ['Kafkas Semenderi', 'Mertensiella caucasica', 'Kafkas Semenderi Tür Koruma Eylem Planı Kitabı.pdf'],
  ['Karadeniz Alabalığı', 'Salmo labrax', 'Karadenizalasi.pdf'],
  ['Kelaynak', 'Geronticus eremita', 'Kelaynak Tür Eylem Planı.pdf'],
  ['Marmaris Semenderi', 'Lyciasalamandra flavimembris', 'Marmaris Semenderi Tür Eylem Planı 09.07.2018.pdf'],
  ['Mersin İli Akdeniz Foku', 'Monachus monachus', 'MersinFok.pdf'],
  ['Muğla İli Akdeniz Foku', 'Monachus monachus', 'MuglaFok1.pdf'],
  ['Çöl Varanı', 'Varanus griseus', 'Nihai Rapor_Varan (1).pdf'],
  ['Sakallı Yarasa', 'Myotis mystacinus', 'SaklliYrs.pdf'],
  ['Saz Kedisi', 'Felis chaus', 'Sazkedisi.pdf'],
  ['Siraz Balığı', '', 'Siraz.pdf'],
  ['Tavas Kurbağası', 'Rana tavasensis', 'Tavas kurbağası tür eylem planı 64 sayfa.pdf'],
  ['Tepeli Pelikan', 'Pelecanus crispus', 'Tepeli Pelikan Eylem Planı_V3.8 12.pdf'],
  ['Toy', 'Otis tarda', 'Toy.pdf'],
  ['Turna', 'Grus grus', 'Turna.pdf'],
  ['Trakya Tosbağası', 'Testudo hermanni', 'Tür Eylem Planı Testudo hermanni.pdf'],
  ['Van Kertenkelesi', 'Darevskia sapphirina', 'Van Kertenkelesi.pdf'],
  ['Yer Yediuyuru', 'Myomimus roachi', 'Yer7uyuru.pdf'],
];

export const flora = [
  ['Avanos Keveni', 'Acantholimon avanosicum'],
  ['Sarı Dağ Gülü', 'Adonis cyllenea var. paryadrica'],
  ['Karaman Kayagülü', 'Aethionema karamanicum'],
  ['Kabamayasıl', 'Ajuga xylorrhiza'],
  ['Yalı Havacivası', 'Alkanna mughlae'],
  ['Nezaket Kevkesi', 'Alyssum nezaketiae'],
  ['Gövrek', 'Anchusa limbata'],
  ['Tuz Kırgını', 'Asparagus lycaonicus'],
  ['Beypazarı Geveni', 'Astragalus beypazaricus'],
  ['Er Geveni', 'Astragalus bozakmanii'],
  ['Niğde Obrizyası', 'Aubrieta vulcanica'],
  ['Edirne Sümbülü', 'Bellevalia edirnensis'],
  ['Ayaş Çançiçeği', 'Campanula damboldtiana'],
  ['Tüylü Çançiçeği', 'Campanula tomentosa'],
  ['İspir Çıngırağı', 'Campanula troegerae'],
  ['Kulindor', 'Centaurea hermannii'],
  ['Peygamber Çiçeği', 'Centaurea aksoyi'],
  ['Sultan Pelemiri', 'Cephalaria tuteliana'],
  ['Sinop Çiğdemi', 'Crocus speciosus subsp. xantholaimos'],
  ['Kızıl Kaplanotu', 'Dorycnium sanguineum'],
  ['Seçmen Çakşırı', 'Ekimia ozcan-secmenii'],
  ['Güdük İğnelik', 'Erodium hendrikii'],
  ['Kerkür', 'Ferula mervynii'],
  ['Baskil Lalesi', 'Fritillaria baskilensis'],
  ['Truva Kardeleni', 'Galanthus trojanus'],
  ['Sarı Afat', 'Gentiana lutea'],
  ['Konya Meyanı', 'Glycyrrhiza iconica'],
  ['Sümbül', 'Hyacinthus orientalis subsp. chionophilus'],
  ['Tuz Beğendiotu', 'Iberis halophila'],
  ['Kır Navruzu', 'Iris farashae'],
  ['Peşmen Navruzu', 'Iris peshmeniana'],
  ['Yer Sasalı', 'Ornithogalum malatyanum'],
  ['Malatya Kantaronu', 'Hypericum malatyanum'],
  ['Ak Navruz', 'Iris stenophylla subsp. margaretiae'],
  ['Ak Zambak', 'Lilium candidum'],
  ['Kum Emziği', 'Onosma propontica'],
  ['Gezertere', 'Physoptychis hausknechtii'],
  ['Samsun Madımağı', 'Polygonum samsunicum'],
  ['Dişli Çakşı', 'Prangos denticulata'],
  ['Has Tülübaşı', 'Psephellus brevifimbriatus'],
  ['Koyak Tülübaşı', 'Psephellus hadimensis'],
  ['Yurt Tülübaşı', 'Psephellus turcicus'],
  ['Mevzek', 'Pseudodelphinium turcicum'],
  ['Aydın Gaşağı', 'Rhaponticoides mykalea'],
  ['Dağ Gülü', 'Rhodothamnus sessilifolius'],
  ['Dicle Koruğu', 'Rosularia blepharophylla'],
  ['Koca Soda', 'Salsola grandis'],
  ['Siirt Adaçayı', 'Salvia siirtica'],
  ['Karaüşmen', 'Saponaria karapinarensis'],
  ['Hoş Sümbül', 'Scilla mesopotamica'],
  ['Trabzon Kanaryaotu', 'Senecio trapezuntinus'],
  ['Bozdağ Sivri Çayı', 'Sideritis tmolea'],
  ['Denizli Nakılı', 'Silene denizliensis'],
  ['Testi Otu', 'Amphoricarpos praedictus'],
  ['Erzincan Sütotu', 'Sonchus erzincanicus'],
  ['Çarşak Çayı', 'Stachys bayburtensis'],
  ['Allıgelin', 'Tchihatchewia isatidea'],
  ['Eber Sarısı', 'Thermopsis turcica'],
  ['Manisa Lalesi', 'Tulipa orphanidea'],
  ['Terli Sığırkuyruğu', 'Verbascum adenocaulon'],
  ['Riva Sığırkuyruğu', 'Verbascum bugulifolium'],
  ['Sığırkuyruğu', 'Verbascum eskisehirensis'],
  ['Gök Sığırkuyruğu', 'Verbascum yurtkuranium'],
  ['Karacafiği', 'Vicia parvula'],
];
